---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: 2.7-slim

inputs:
- name: opa-boshrelease

run:
  path: bash
  dir: opa-boshrelease
  args:
  - -euc
  - |
    bundle install
    bundle exec rspec spec/
